name: CI
on:
  - pull_request
  - push
jobs:
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
         - 8.0
         - 8.1
    services:
      mqtt:
        image: spants/mqtt
        ports:
          - 1883:1883
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
